// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6dRh6eW3w0nciyjW5hy9aK-HrIgnu1wo',
    appId: '1:56128500859:web:d1e2c41400be6614d95ede',
    messagingSenderId: '56128500859',
    projectId: 'notes-31ca8',
    authDomain: 'notes-31ca8.firebaseapp.com',
    storageBucket: 'notes-31ca8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO3J01LJJw7WB_qrGEoHToUTj1beF-6kw',
    appId: '1:56128500859:android:d026f887a31cc8f3d95ede',
    messagingSenderId: '56128500859',
    projectId: 'notes-31ca8',
    storageBucket: 'notes-31ca8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5oVIsFhdX2Xc-LNVW7OmbEWvaL5VqcAc',
    appId: '1:56128500859:ios:db5652db1044d354d95ede',
    messagingSenderId: '56128500859',
    projectId: 'notes-31ca8',
    storageBucket: 'notes-31ca8.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5oVIsFhdX2Xc-LNVW7OmbEWvaL5VqcAc',
    appId: '1:56128500859:ios:db5652db1044d354d95ede',
    messagingSenderId: '56128500859',
    projectId: 'notes-31ca8',
    storageBucket: 'notes-31ca8.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6dRh6eW3w0nciyjW5hy9aK-HrIgnu1wo',
    appId: '1:56128500859:web:15875174bc7cd9c1d95ede',
    messagingSenderId: '56128500859',
    projectId: 'notes-31ca8',
    authDomain: 'notes-31ca8.firebaseapp.com',
    storageBucket: 'notes-31ca8.appspot.com',
  );
}
